services:
  - type: web
    name: james-ai-idea
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd app/static
      npm install
      npm run build
      cd ../..
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false 
